### ISSUE TITLE
It'd be useful to have the sources added for everything

### ISSUE THREAD

**Issue by xdy** [TikaelSol/PF2e-Expansion-Pack#1]
Which, of course, means that I'm volunteering to add them. :) (For the books I own at least.)
(As several smaller PRs, probably one per supplement.)

But, if you're interested in that, what should the sources be? I'm thinking of using the following:

"Files For Everybody: name of supplement" e.g. "Files For Everybody: Nashi"
"Ancestries Unleashed: name of supplement" e.g. "Ancestries Unleashed: Rabbitfolk"
"Luis Loza Blog" I.e. one source for all his blog posts
"Logan Bonner Games: The Pnoll: An Ancestry" Or maybe skip the "Logan Bonner Games:" part, but I do like making it easy to find the supplements.
"Eldritch Ancestries: <name of ancestry>" e.g. "Eldritch Ancestries: Felsine"

But, where do Tinker Archetype, Magitechnician, Tanuki, Gunpowder Alchemist come from?

(Oh, and I do wish that source also had an 'url' field. Possibly even a 'page number'. But, that's way off topic for this github issue.)

**Comment by TikaelSol** [comment]
Tinker, magitechnician, tanuki, and gunpowder alchemist all come from the Nashi PDF.  I would like to add sources but since Foundry does not surface that field I cannot edit it without either editing the db files (bad idea), or setting up an Extract Packs program (complicated).  I will see if I can't get the main system to surface the source field though.  Data entry for the system would be easier then as well.

**Comment by xdy** [comment]
Oh, right. I bought that but haven't actually looked through it properly yet. :)

This issue comes off of my recent flood of source-adding PRs for the system. TMun asked if someone wanted to do it and got me a dump from AON, I went wild (with a horrible little script) from there. I figure as he asked he intends for source to at least be a filter in the compendium browser. Hopefully it'll end up visible/editable on items as well.
I know I want it, so, worst case, I'll have to buckle down and do a system PR for it myself. :)

**Comment by ianblackstone** [comment]
Sources for all feats have been added.

**Comment by TikaelSol** [comment]
Sources have been added
