### ISSUE TITLE
Not verified for Foundry v11 yet

### ISSUE THREAD

**Issue by wlbateman193** [TikaelSol/PF2e-Expansion-Pack#6]
I have not encountered any issues with this module on Foundry v11 yet, but Foundry reports that it is last verified for v10.288 and thus shows up with a yellow warning indicator on the Add-on Modules screen in Foundry

**Comment by caniko** [comment]
Yeah, it is not working anymore :(

**Comment by TikaelSol** [comment]
> Yeah, it is not working anymore :(

Right click the compendium and unlock, then check the migration status and run the migration and it will work. I don't plan on updating this any time soon, but potentially this fall I'll return to do a major revamp of the module if I have time.
